#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
DATA_DIR="${REPO_ROOT}/data"

if [[ -z "${OPNOVICE_BIN:-}" && -x "${REPO_ROOT}/app-build/OpNovice2" ]]; then
  export OPNOVICE_BIN="${REPO_ROOT}/app-build/OpNovice2"
fi

STUDY_ROOT="${STUDY_ROOT:-${DATA_DIR}/spatial_angle_study}"
RUN_LABEL="${RUN_LABEL:-$(date +%Y%m%d_%H%M%S)}"
RUN_ROOT="${STUDY_ROOT}/runs/${RUN_LABEL}"
MACRO_DIR="${REPO_ROOT}/scripts/macros/spatial_angle/generated/${RUN_LABEL}"
SUMMARY_CSV="${RUN_ROOT}/run_summary.csv"

ANGLE_PAIRS="${ANGLE_PAIRS:-0,0 45,0 0,45 30,30 45,45 60,30}"
BEAM_ON="${BEAM_ON:-1000}"
ENERGY_KEV="${ENERGY_KEV:-662}"

DETECTOR_THICKNESS_MM="${DETECTOR_THICKNESS_MM:-10}"
DETECTOR_SIDE_LENGTH_MM="${DETECTOR_SIDE_LENGTH_MM:-51}"
DETECTOR_WIDTH_MM="${DETECTOR_WIDTH_MM:-51}"
DETECTOR_SECTION="${DETECTOR_SECTION:-1}"
DETECTOR_HAS_REFLECTOR="${DETECTOR_HAS_REFLECTOR:-1}"
DETECTOR_HAS_HOUSING="${DETECTOR_HAS_HOUSING:-0}"
DETECTOR_MATERIAL="${DETECTOR_MATERIAL:-0}"
NUMBER_OF_SIPM="${NUMBER_OF_SIPM:-1}"
REFLECTOR_TYPE="${REFLECTOR_TYPE:-0}"

# Keep the same default z as the previous incidence-angle study. Position is in cm in the macro.
SOURCE_Z_MM="${SOURCE_Z_MM:--9.0}"

log() {
  printf '[spatial] %s\n' "$*"
}

die() {
  printf '[spatial] ERROR: %s\n' "$*" >&2
  exit 1
}

angle_slug() {
  local angle="$1"
  printf '%s' "${angle}" | tr '.-' 'pm'
}

case_name() {
  local ax="$1"
  local ay="$2"
  printf 'ax_%sdeg_ay_%sdeg' "$(angle_slug "${ax}")" "$(angle_slug "${ay}")"
}

collect_root_results() {
  local target_dir="$1"
  shopt -s nullglob
  local files=("${DATA_DIR}"/results_*.csv)
  if (( ${#files[@]} == 0 )); then
    shopt -u nullglob
    return 0
  fi
  mkdir -p "${target_dir}"
  local f
  for f in "${files[@]}"; do
    mv -- "${f}" "${target_dir}/"
  done
  shopt -u nullglob
}

python_calc() {
  python3 - "$@" <<'PY'
import math
import sys

mode = sys.argv[1]
ax_deg = float(sys.argv[2])
ay_deg = float(sys.argv[3])
thickness_mm = float(sys.argv[4])
has_reflector = int(sys.argv[5])
source_z_mm = float(sys.argv[6])

if abs(ax_deg) >= 89.9 or abs(ay_deg) >= 89.9:
    raise SystemExit("angle components must stay below 89.9 deg")

reflector_half_mm = 1.5 if has_reflector else 0.0
front_z_mm = -(thickness_mm / 2.0 + 2.0 * reflector_half_mm)
distance_to_front_mm = front_z_mm - source_z_mm
tan_x = math.tan(math.radians(ax_deg))
tan_y = math.tan(math.radians(ay_deg))
norm = math.sqrt(tan_x * tan_x + tan_y * tan_y + 1.0)
dx = tan_x / norm
dy = tan_y / norm
dz = 1.0 / norm
theta_eff = math.degrees(math.acos(dz))
phi_eff = math.degrees(math.atan2(dy, dx)) if (dx or dy) else 0.0

if mode == "direction":
    print(f"{dx:.12g} {dy:.12g} {dz:.12g}")
elif mode == "position":
    x_mm = -tan_x * distance_to_front_mm
    y_mm = -tan_y * distance_to_front_mm
    print(f"{x_mm / 10.0:.12g} {y_mm / 10.0:.12g} {source_z_mm / 10.0:.12g} cm")
elif mode == "front_z":
    print(f"{front_z_mm:.12g}")
elif mode == "theta_eff":
    print(f"{theta_eff:.12g}")
elif mode == "phi_eff":
    print(f"{phi_eff:.12g}")
else:
    raise SystemExit(f"unknown mode: {mode}")
PY
}

build_macro() {
  local ax="$1"
  local ay="$2"
  local macro_path="$3"
  local dir_vec pos_vec front_z theta_eff phi_eff
  dir_vec="$(python_calc direction "${ax}" "${ay}" "${DETECTOR_THICKNESS_MM}" "${DETECTOR_HAS_REFLECTOR}" "${SOURCE_Z_MM}")"
  pos_vec="$(python_calc position "${ax}" "${ay}" "${DETECTOR_THICKNESS_MM}" "${DETECTOR_HAS_REFLECTOR}" "${SOURCE_Z_MM}")"
  front_z="$(python_calc front_z "${ax}" "${ay}" "${DETECTOR_THICKNESS_MM}" "${DETECTOR_HAS_REFLECTOR}" "${SOURCE_Z_MM}")"
  theta_eff="$(python_calc theta_eff "${ax}" "${ay}" "${DETECTOR_THICKNESS_MM}" "${DETECTOR_HAS_REFLECTOR}" "${SOURCE_Z_MM}")"
  phi_eff="$(python_calc phi_eff "${ax}" "${ay}" "${DETECTOR_THICKNESS_MM}" "${DETECTOR_HAS_REFLECTOR}" "${SOURCE_Z_MM}")"

  mkdir -p "$(dirname "${macro_path}")"
  cat > "${macro_path}" <<EOF
### Spatial angle study: full output, generated by scripts/run_spatial_angle_study.sh
### angle_x_deg=${ax}
### angle_y_deg=${ay}
### effective_polar_theta_deg=${theta_eff}
### effective_azimuth_phi_deg=${phi_eff}
### source_z_mm=${SOURCE_Z_MM}
### aimed_front_z_mm=${front_z}
/tracking/verbose -1
/process/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/storeTrajectory 0

/process/em/auger 1
/process/em/augerCascade 1
/process/em/deexcitationIgnoreCut 1

/analysis/setActivation 1
/analysis/ntuple/setActivationToAll 1
/analysis/h1/setActivationToAll 1
/analysis/h2/setActivationToAll 1

/opnovice2/detector/setDetectorSection ${DETECTOR_SECTION}
/opnovice2/detector/setDetectorThickness ${DETECTOR_THICKNESS_MM}
/opnovice2/detector/setDetectorSideLength ${DETECTOR_SIDE_LENGTH_MM}
/opnovice2/detector/setDetectorWidth ${DETECTOR_WIDTH_MM}
/opnovice2/detector/detectorHasReflector ${DETECTOR_HAS_REFLECTOR}
/opnovice2/detector/setReflectorType ${REFLECTOR_TYPE}
/opnovice2/detector/detectorHasHousing ${DETECTOR_HAS_HOUSING}
/opnovice2/detector/setNumberOfSiPM ${NUMBER_OF_SIPM}
/opnovice2/detector/setDetectorMaterial ${DETECTOR_MATERIAL}

/gun/position ${pos_vec}
/gun/direction ${dir_vec}
/gun/particle gamma
/gun/polarization 0 0 0
/gun/energy ${ENERGY_KEV} keV

/run/beamOn ${BEAM_ON}
EOF
}

append_summary() {
  local ax="$1"
  local ay="$2"
  local case_dir="$3"
  local status="$4"
  local elapsed="$5"
  local theta_eff phi_eff file_count total_bytes
  theta_eff="$(python_calc theta_eff "${ax}" "${ay}" "${DETECTOR_THICKNESS_MM}" "${DETECTOR_HAS_REFLECTOR}" "${SOURCE_Z_MM}")"
  phi_eff="$(python_calc phi_eff "${ax}" "${ay}" "${DETECTOR_THICKNESS_MM}" "${DETECTOR_HAS_REFLECTOR}" "${SOURCE_Z_MM}")"
  file_count="$(find "${case_dir}" -maxdepth 1 -type f -name 'results_*.csv' | wc -l)"
  total_bytes="$(find "${case_dir}" -maxdepth 1 -type f -name 'results_*.csv' -printf '%s\n' | awk '{s+=$1} END {print s+0}')"
  printf '%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n' \
    "${RUN_LABEL}" "${ax}" "${ay}" "${theta_eff}" "${phi_eff}" "${BEAM_ON}" "${ENERGY_KEV}" "${status}" "${elapsed}" "${file_count}" "${total_bytes}" \
    >> "${SUMMARY_CSV}"
}

run_case() {
  local ax="$1"
  local ay="$2"
  local slug case_dir macro_path start_s end_s elapsed status dir_vec pos_vec theta_eff phi_eff
  slug="$(case_name "${ax}" "${ay}")"
  case_dir="${RUN_ROOT}/${slug}"
  macro_path="${MACRO_DIR}/${slug}.mac"

  if [[ -f "${case_dir}/run_status.txt" ]] && grep -q '^status=0$' "${case_dir}/run_status.txt"; then
    log "Skipping existing completed ax=${ax} deg, ay=${ay} deg"
    return 0
  fi

  mkdir -p "${case_dir}"
  build_macro "${ax}" "${ay}" "${macro_path}"
  cp "${macro_path}" "${case_dir}/run.mac"

  dir_vec="$(python_calc direction "${ax}" "${ay}" "${DETECTOR_THICKNESS_MM}" "${DETECTOR_HAS_REFLECTOR}" "${SOURCE_Z_MM}")"
  pos_vec="$(python_calc position "${ax}" "${ay}" "${DETECTOR_THICKNESS_MM}" "${DETECTOR_HAS_REFLECTOR}" "${SOURCE_Z_MM}")"
  theta_eff="$(python_calc theta_eff "${ax}" "${ay}" "${DETECTOR_THICKNESS_MM}" "${DETECTOR_HAS_REFLECTOR}" "${SOURCE_Z_MM}")"
  phi_eff="$(python_calc phi_eff "${ax}" "${ay}" "${DETECTOR_THICKNESS_MM}" "${DETECTOR_HAS_REFLECTOR}" "${SOURCE_Z_MM}")"

  collect_root_results "${RUN_ROOT}/preexisting_root_results"

  log "Running ax=${ax} deg, ay=${ay} deg, theta_eff=${theta_eff} deg, beamOn=${BEAM_ON}, energy=${ENERGY_KEV} keV"
  start_s="$(date +%s)"
  set +e
  "${REPO_ROOT}/scripts/run_batch.sh" "${macro_path}" | tee "${case_dir}/run.log"
  status="${PIPESTATUS[0]}"
  set -e
  end_s="$(date +%s)"
  elapsed=$((end_s - start_s))

  collect_root_results "${case_dir}"

  {
    printf 'status=%s\n' "${status}"
    printf 'elapsed_seconds=%s\n' "${elapsed}"
    printf 'angle_x_deg=%s\n' "${ax}"
    printf 'angle_y_deg=%s\n' "${ay}"
    printf 'effective_polar_theta_deg=%s\n' "${theta_eff}"
    printf 'effective_azimuth_phi_deg=%s\n' "${phi_eff}"
    printf 'gun_direction=%s\n' "${dir_vec}"
    printf 'gun_position=%s\n' "${pos_vec}"
    printf 'beam_on=%s\n' "${BEAM_ON}"
    printf 'energy_keV=%s\n' "${ENERGY_KEV}"
    printf 'detector_width_mm=%s\n' "${DETECTOR_WIDTH_MM}"
    printf 'detector_side_length_mm=%s\n' "${DETECTOR_SIDE_LENGTH_MM}"
    printf 'number_of_sipm=%s\n' "${NUMBER_OF_SIPM}"
    printf 'detector_has_reflector=%s\n' "${DETECTOR_HAS_REFLECTOR}"
  } > "${case_dir}/run_status.txt"

  append_summary "${ax}" "${ay}" "${case_dir}" "${status}" "${elapsed}"

  if [[ -f "${REPO_ROOT}/scripts/check_spatial_angle_outputs.py" ]]; then
    python3 "${REPO_ROOT}/scripts/check_spatial_angle_outputs.py" \
      --run-root "${RUN_ROOT}" \
      --ax "${ax}" \
      --ay "${ay}" \
      --write-summary
  fi

  if (( status != 0 )); then
    die "run failed for ax=${ax} deg, ay=${ay} deg; archived partial outputs in ${case_dir}"
  fi
}

main() {
  mkdir -p "${RUN_ROOT}" "${MACRO_DIR}"
  if [[ ! -f "${SUMMARY_CSV}" ]]; then
    printf 'run_label,angle_x_deg,angle_y_deg,effective_polar_theta_deg,effective_azimuth_phi_deg,beam_on,energy_keV,status,elapsed_seconds,output_files,output_total_bytes\n' > "${SUMMARY_CSV}"
  fi

  log "Run root: ${RUN_ROOT}"
  log "Angle pairs: ${ANGLE_PAIRS}"
  log "Use a caller timeout above the estimated batch runtime."

  local pair ax ay
  for pair in ${ANGLE_PAIRS}; do
    IFS=',' read -r ax ay <<< "${pair}"
    if [[ -z "${ax}" || -z "${ay}" ]]; then
      die "Invalid angle pair '${pair}'; expected ax,ay"
    fi
    run_case "${ax}" "${ay}"
  done

  log "Complete. Archived outputs under ${RUN_ROOT}"
}

main "$@"
