#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
DATA_DIR="${REPO_ROOT}/data"

if [[ -z "${OPNOVICE_BIN:-}" && -x "${REPO_ROOT}/app-build/OpNovice2" ]]; then
  export OPNOVICE_BIN="${REPO_ROOT}/app-build/OpNovice2"
fi

STUDY_ROOT="${STUDY_ROOT:-${DATA_DIR}/incidence_angle_study}"
RUN_LABEL="${RUN_LABEL:-$(date +%Y%m%d_%H%M%S)}"
RUN_ROOT="${STUDY_ROOT}/runs/${RUN_LABEL}"
MACRO_DIR="${REPO_ROOT}/scripts/macros/incidence_angle/generated/${RUN_LABEL}"
SUMMARY_CSV="${RUN_ROOT}/run_summary.csv"

ANGLES="${ANGLES:-0 15 30 45 60 75 85}"
BEAM_ON="${BEAM_ON:-1000}"
ENERGY_KEV="${ENERGY_KEV:-662}"

DETECTOR_THICKNESS_MM="${DETECTOR_THICKNESS_MM:-10}"
DETECTOR_SIDE_LENGTH_MM="${DETECTOR_SIDE_LENGTH_MM:-51}"
DETECTOR_WIDTH_MM="${DETECTOR_WIDTH_MM:-51}"
DETECTOR_SECTION="${DETECTOR_SECTION:-1}"
DETECTOR_HAS_REFLECTOR="${DETECTOR_HAS_REFLECTOR:-1}"
DETECTOR_HAS_HOUSING="${DETECTOR_HAS_HOUSING:-0}"
DETECTOR_MATERIAL="${DETECTOR_MATERIAL:-0}"
NUMBER_OF_SIPM="${NUMBER_OF_SIPM:-1}"
REFLECTOR_TYPE="${REFLECTOR_TYPE:-0}"

# Keep the same default z as default.mac. Position is in cm in the macro.
SOURCE_Z_MM="${SOURCE_Z_MM:--9.0}"

log() {
  printf '[incidence] %s\n' "$*"
}

die() {
  printf '[incidence] ERROR: %s\n' "$*" >&2
  exit 1
}

angle_slug() {
  local angle="$1"
  printf '%s' "${angle}" | tr '.-' 'pm'
}

collect_root_results() {
  local target_dir="$1"
  shopt -s nullglob
  local files=("${DATA_DIR}"/results_*.csv)
  if (( ${#files[@]} == 0 )); then
    shopt -u nullglob
    return 0
  fi
  mkdir -p "${target_dir}"
  local f
  for f in "${files[@]}"; do
    mv -- "${f}" "${target_dir}/"
  done
  shopt -u nullglob
}

python_calc() {
  python3 - "$@" <<'PY'
import math
import sys

mode = sys.argv[1]
angle_deg = float(sys.argv[2])
thickness_mm = float(sys.argv[3])
has_reflector = int(sys.argv[4])
source_z_mm = float(sys.argv[5])

reflector_half_mm = 1.5 if has_reflector else 0.0
front_z_mm = -(thickness_mm / 2.0 + 2.0 * reflector_half_mm)
distance_to_front_mm = front_z_mm - source_z_mm
theta = math.radians(angle_deg)

if mode == "direction":
    print(f"{math.sin(theta):.12g} 0 {math.cos(theta):.12g}")
elif mode == "position":
    x_mm = -math.tan(theta) * distance_to_front_mm
    print(f"{x_mm / 10.0:.12g} 0 {source_z_mm / 10.0:.12g} cm")
elif mode == "front_z":
    print(f"{front_z_mm:.12g}")
else:
    raise SystemExit(f"unknown mode: {mode}")
PY
}

build_macro() {
  local angle="$1"
  local macro_path="$2"
  local dir_vec pos_vec front_z
  dir_vec="$(python_calc direction "${angle}" "${DETECTOR_THICKNESS_MM}" "${DETECTOR_HAS_REFLECTOR}" "${SOURCE_Z_MM}")"
  pos_vec="$(python_calc position "${angle}" "${DETECTOR_THICKNESS_MM}" "${DETECTOR_HAS_REFLECTOR}" "${SOURCE_Z_MM}")"
  front_z="$(python_calc front_z "${angle}" "${DETECTOR_THICKNESS_MM}" "${DETECTOR_HAS_REFLECTOR}" "${SOURCE_Z_MM}")"

  mkdir -p "$(dirname "${macro_path}")"
  cat > "${macro_path}" <<EOF
### Incidence angle study: full output, generated by scripts/run_incidence_angle_study.sh
### angle_deg=${angle}
### source_z_mm=${SOURCE_Z_MM}
### aimed_front_z_mm=${front_z}
/tracking/verbose -1
/process/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/storeTrajectory 0

/process/em/auger 1
/process/em/augerCascade 1
/process/em/deexcitationIgnoreCut 1

/analysis/setActivation 1
/analysis/ntuple/setActivationToAll 1
/analysis/h1/setActivationToAll 1
/analysis/h2/setActivationToAll 1

/opnovice2/detector/setDetectorSection ${DETECTOR_SECTION}
/opnovice2/detector/setDetectorThickness ${DETECTOR_THICKNESS_MM}
/opnovice2/detector/setDetectorSideLength ${DETECTOR_SIDE_LENGTH_MM}
/opnovice2/detector/setDetectorWidth ${DETECTOR_WIDTH_MM}
/opnovice2/detector/detectorHasReflector ${DETECTOR_HAS_REFLECTOR}
/opnovice2/detector/setReflectorType ${REFLECTOR_TYPE}
/opnovice2/detector/detectorHasHousing ${DETECTOR_HAS_HOUSING}
/opnovice2/detector/setNumberOfSiPM ${NUMBER_OF_SIPM}
/opnovice2/detector/setDetectorMaterial ${DETECTOR_MATERIAL}

/gun/position ${pos_vec}
/gun/direction ${dir_vec}
/gun/particle gamma
/gun/polarization 0 0 0
/gun/energy ${ENERGY_KEV} keV

/run/beamOn ${BEAM_ON}
EOF
}

append_summary() {
  local angle="$1"
  local case_dir="$2"
  local status="$3"
  local elapsed="$4"
  local file_count total_bytes
  file_count="$(find "${case_dir}" -maxdepth 1 -type f -name 'results_*.csv' | wc -l)"
  total_bytes="$(find "${case_dir}" -maxdepth 1 -type f -name 'results_*.csv' -printf '%s\n' | awk '{s+=$1} END {print s+0}')"
  printf '%s,%s,%s,%s,%s,%s,%s,%s\n' \
    "${RUN_LABEL}" "${angle}" "${BEAM_ON}" "${ENERGY_KEV}" "${status}" "${elapsed}" "${file_count}" "${total_bytes}" \
    >> "${SUMMARY_CSV}"
}

run_case() {
  local angle="$1"
  local slug case_dir macro_path start_s end_s elapsed status
  slug="$(angle_slug "${angle}")"
  case_dir="${RUN_ROOT}/angle_${slug}deg"
  macro_path="${MACRO_DIR}/angle_${slug}deg.mac"

  if [[ -f "${case_dir}/run_status.txt" ]] && grep -q '^status=0$' "${case_dir}/run_status.txt"; then
    log "Skipping existing completed angle=${angle} deg"
    return 0
  fi

  mkdir -p "${case_dir}"
  build_macro "${angle}" "${macro_path}"
  cp "${macro_path}" "${case_dir}/run.mac"

  collect_root_results "${RUN_ROOT}/preexisting_root_results"

  log "Running angle=${angle} deg, beamOn=${BEAM_ON}, energy=${ENERGY_KEV} keV"
  start_s="$(date +%s)"
  set +e
  "${REPO_ROOT}/scripts/run_batch.sh" "${macro_path}" | tee "${case_dir}/run.log"
  status="${PIPESTATUS[0]}"
  set -e
  end_s="$(date +%s)"
  elapsed=$((end_s - start_s))

  collect_root_results "${case_dir}"

  {
    printf 'status=%s\n' "${status}"
    printf 'elapsed_seconds=%s\n' "${elapsed}"
    printf 'angle_deg=%s\n' "${angle}"
    printf 'beam_on=%s\n' "${BEAM_ON}"
    printf 'energy_keV=%s\n' "${ENERGY_KEV}"
    printf 'detector_width_mm=%s\n' "${DETECTOR_WIDTH_MM}"
    printf 'detector_side_length_mm=%s\n' "${DETECTOR_SIDE_LENGTH_MM}"
    printf 'number_of_sipm=%s\n' "${NUMBER_OF_SIPM}"
    printf 'detector_has_reflector=%s\n' "${DETECTOR_HAS_REFLECTOR}"
  } > "${case_dir}/run_status.txt"

  append_summary "${angle}" "${case_dir}" "${status}" "${elapsed}"

  if [[ -f "${REPO_ROOT}/scripts/check_incidence_angle_outputs.py" ]]; then
    python3 "${REPO_ROOT}/scripts/check_incidence_angle_outputs.py" \
      --run-root "${RUN_ROOT}" \
      --angle "${angle}" \
      --write-summary
  fi

  if (( status != 0 )); then
    die "run failed for angle=${angle} deg; archived partial outputs in ${case_dir}"
  fi
}

main() {
  mkdir -p "${RUN_ROOT}" "${MACRO_DIR}"
  if [[ ! -f "${SUMMARY_CSV}" ]]; then
    printf 'run_label,angle_deg,beam_on,energy_keV,status,elapsed_seconds,output_files,output_total_bytes\n' > "${SUMMARY_CSV}"
  fi

  log "Run root: ${RUN_ROOT}"
  log "Angles: ${ANGLES}"
  log "Estimated first-run timeout should exceed the caller's per-command timeout."

  local angle
  for angle in ${ANGLES}; do
    run_case "${angle}"
  done

  log "Complete. Archived outputs under ${RUN_ROOT}"
}

main "$@"
